package google

import (
	"context"
	"time"

	"github.com/dstotijn/go-notion"
	"google.golang.org/api/calendar/v3"
)

// CreateEvents ...
func (g *CalendarService) CreateEvent(calendarID string, notInGCal *notion.DatabaseQueryResponse, client *notion.Client) error {
	srv := g.Client
	ctx := context.Background()

	// Create Event(s) in G-Cal
	for _, u := range notInGCal.Results {
		if val, ok := u.Properties.(notion.DatabasePageProperties); ok {
			// Retrieve Event info from Notion
			summary := val["Name"].Title[0].Text.Content
			startTime := val["Date"].Date.Start.Time.Format(time.RFC3339)
			endTime := val["Date"].Date.End.Time.Format(time.RFC3339)

			// Create Event Object to be Inserted
			event := &calendar.Event{
				Summary: summary,
				Start: &calendar.EventDateTime{
					DateTime: startTime,
					TimeZone: startTime,
				},
				End: &calendar.EventDateTime{
					DateTime: endTime,
					TimeZone: endTime,
				},
			}

			// Insert Event into G-Cal
			event, err := srv.Events.Insert(calendarID, event).Do()
			if err != nil {
				return err
			}

			// Update Notion with the GCal_ID Generated by G-Cal after the Event is Inserted
			_, err = client.UpdatePageProps(ctx, u.ID, notion.UpdatePageParams{
				DatabasePageProperties: &notion.DatabasePageProperties{
					"GCal_ID": notion.DatabasePageProperty{
						RichText: []notion.RichText{
							{
								Type: notion.RichTextTypeText,
								Text: &notion.Text{
									Content: event.Id,
								},
							},
						},
					},
				},
			})
			if err != nil {
				return err
			}
		}
	}
	return nil
}
